// gen.mjs — generate v011b ui-web batch (translator-a · t17)
// Run: node zh-dict/batches/v011b/ui-web/gen.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', '..', '..');

const raw = (p) => readFileSync(join(root, p), 'utf8');

// ---------------- translations: [scope, source, target, anchor?] ----------------
const E = [
  // --- batch1.tsv (ui) real translations, long-source-first applied later ---
  ['ui', `${'$'}{leftovers.length} change${'$'}{leftovers.length === 1 ? '' : 's'} could not be discarded (${'$'}{listed}). Submodule changes must be discarded inside the submodule repository.`,
   `${'$'}{leftovers.length} 个更改无法丢弃（${'$'}{listed}）。子模块的更改必须在子模块仓库内丢弃。`],
  ['ui', 'Every staged file goes back to the last commit, unstaged edits to those files included, and new files are deleted. This cannot be undone — not even with ⌘Z.',
   '每个已暂存的文件都会回到最后一次提交，这些文件的未暂存编辑也一并还原，新文件会被删除。此操作无法撤销——即使按 ⌘Z 也不行。'],
  ['ui', 'These files go back to the last commit — staged and unstaged changes alike. New files are deleted. This cannot be undone.',
   '这些文件将回到最后一次提交——已暂存与未暂存的更改都会一并还原。新文件会被删除。此操作无法撤销。'],
  ['ui', 'The file goes back to the last commit — its staged and unstaged changes are both reverted. This cannot be undone.',
   '该文件将回到最后一次提交——其已暂存与未暂存的更改都会被还原。此操作无法撤销。'],
  ['ui', 'All changes in these files will be reverted. Untracked files among them are deleted. This cannot be undone.',
   '这些文件中的所有更改将被还原，其中的未跟踪文件会被删除。此操作无法撤销。'],
  ['ui', `This ${'$'}{forgeNoun(forgeRemote?.kind)} cannot be checked out from AngKorGit — open it in the browser instead.`,
   `无法从 AngKorGit 检出此${'$'}{forgeNoun(forgeRemote?.kind)}——请改在浏览器中打开。`],
  ['ui', `${'$'}{remaining.length} staged change${'$'}{remaining.length === 1 ? '' : 's'} could not be discarded: ${'$'}{listed}`,
   `${'$'}{remaining.length} 个已暂存更改无法丢弃：${'$'}{listed}`],
  ['ui', 'This file is new — discarding removes it from the index and deletes the file. This cannot be undone.',
   '该文件是新增文件——丢弃会将其从索引中移除并删除文件。此操作无法撤销。'],
  ['ui', `${'$'}{leftovers.length} change${'$'}{leftovers.length === 1 ? '' : 's'} could not be discarded: ${'$'}{listed}`,
   `${'$'}{leftovers.length} 个更改无法丢弃：${'$'}{listed}`],
  ['ui', `Only these ${'$'}{stashPaths.length} files are stashed. Everything else stays in your working copy.`,
   `仅这 ${'$'}{stashPaths.length} 个文件被暂存，其余内容保留在工作副本中。`],
  ['ui', `${'$'}{local.ahead} commit${'$'}{local.ahead === 1 ? '' : 's'} only on the local branch will be lost.`,
   `${'$'}{local.ahead} 个提交仅存在于本地分支，将被丢弃。`],
  ['ui', `AngKorGit error report\\n\\n${'$'}{error?.name}: ${'$'}{error?.message}\\n\\n${'$'}{error?.stack ?? ''}`,
   `AngKorGit 错误报告\\n\\n${'$'}{error?.name}: ${'$'}{error?.message}\\n\\n${'$'}{error?.stack ?? ''}`],
  ['ui', `\\r\\n[could not start shell: ${'$'}{(error as { message?: string }).message ?? error}]`,
   `\\r\\n[无法启动 shell：${'$'}{(error as { message?: string }).message ?? error}]`],
  ['ui', `Checkout ${'$'}{name} failed: ${'$'}{(error as { message?: string }).message ?? error}`,
   `检出 ${'$'}{name} 失败：${'$'}{(error as { message?: string }).message ?? error}`],
  ['ui', 'Only this file is stashed. Everything else stays in your working copy.',
   '仅此文件被暂存，其余内容保留在工作副本中。'],
  ['ui', `Create a ${'$'}{prNoun} for ${'$'}{repo?.headBranch} without leaving AngKorGit`,
   `为 ${'$'}{repo?.headBranch} 创建 ${'$'}{prNoun}，无需离开 AngKorGit`],
  ['ui', `${'$'}{errorLabel}: ${'$'}{(error as { message?: string }).message ?? error}`,
   `${'$'}{errorLabel}：${'$'}{(error as { message?: string }).message ?? error}`],
  ['ui', `Discarded ${'$'}{paths.length} change${'$'}{paths.length === 1 ? '' : 's'}`,
   `已丢弃 ${'$'}{paths.length} 个更改`],
  ['ui', `Redo failed: ${'$'}{(error as { message?: string }).message ?? error}`,
   `重做失败：${'$'}{(error as { message?: string }).message ?? error}`],
  ['ui', `Undo failed: ${'$'}{(error as { message?: string }).message ?? error}`,
   `撤销失败：${'$'}{(error as { message?: string }).message ?? error}`],
  ['ui', `Copied ${'$'}{lines} line${'$'}{lines === 1 ? '' : 's'} (${'$'}{side} text)`,
   `已复制 ${'$'}{lines} 行（${'$'}{side} 文本）`],
  ['ui', `Discarded ${'$'}{before} staged change${'$'}{before === 1 ? '' : 's'}`,
   `已丢弃 ${'$'}{before} 个已暂存更改`],
  ['ui', `Open a pre-filled pull request page for ${'$'}{repo?.headBranch}`,
   `为 ${'$'}{repo?.headBranch} 打开预填的拉取请求页面`],
  ['ui', 'The stashed changes are deleted and cannot be recovered.',
   '暂存的更改将被删除且无法恢复。'],
  ['ui', `Create ${'$'}{forgeNoun(forgeCurrent ? forgeKind : null)}`,
   `创建 ${'$'}{forgeNoun(forgeCurrent ? forgeKind : null)}`],
  ['ui', `detached @ ${'$'}{repo.headOid?.slice(0, 8) ?? '?'}`,
   `游离于 ${'$'}{repo.headOid?.slice(0, 8) ?? '?'}`],
  ['ui', `${'$'}{changes} change${'$'}{changes === 1 ? '' : 's'}`,
   `${'$'}{changes} 个更改`],
  ['ui', `Applied ${'$'}{basename(files[0])} from the stash`,
   `已从暂存中应用 ${'$'}{basename(files[0])}`],
  ['ui', `Applied ${'$'}{files.length} files from the stash`,
   `已从暂存中应用 ${'$'}{files.length} 个文件`],
  ['ui', `detached @ ${'$'}{wt.headOid?.slice(0, 8) ?? '?'}`,
   `游离于 ${'$'}{wt.headOid?.slice(0, 8) ?? '?'}`],
  ['ui', `Discard changes in ${'$'}{paths.length} files?`,
   `丢弃 ${'$'}{paths.length} 个文件中的更改？`],
  ['ui', `From commit ${'$'}{dialogContext.slice(0, 8)}`,
   `来自提交 ${'$'}{dialogContext.slice(0, 8)}`],
  ['ui', `rename ${'$'}{dialogContext} → ${'$'}{name.trim()}`,
   `将 ${'$'}{dialogContext} 重命名为 ${'$'}{name.trim()}`],
  ['ui', `Pop latest stash: ${'$'}{stashes[0].message}`,
   `弹出最新暂存：${'$'}{stashes[0].message}`],
  ['ui', `Unstage ${'$'}{menuMulti.paths.length} files`,
   `取消暂存 ${'$'}{menuMulti.paths.length} 个文件`],
  ['ui', `At commit ${'$'}{dialogContext.slice(0, 8)}`,
   `在提交 ${'$'}{dialogContext.slice(0, 8)}`],
  ['ui', `Stage ${'$'}{menuMulti.paths.length} files`,
   `暂存 ${'$'}{menuMulti.paths.length} 个文件`],
  ['ui', `Worktree ready · ${'$'}{basename(created)}`,
   `工作树已就绪 · ${'$'}{basename(created)}`],
  ['ui', `${'$'}{count} ${'$'}{statusMeta[status].label}`,
   `${'$'}{count} 个${'$'}{statusMeta[status].label}`],
  ['ui', `Cherry-pick ${'$'}{oids[0].slice(0, 8)}`,
   `拣选 ${'$'}{oids[0].slice(0, 8)}`],
  ['ui', `Apply ${'$'}{diff.path} from the stash`,
   `从暂存中应用 ${'$'}{diff.path}`],
  ['ui', 'No staged files match the filter.',
   '没有匹配过滤条件的已暂存文件。'],
  ['ui', `Reset ${'$'}{name} to ${'$'}{ref.shorthand}`,
   `将 ${'$'}{name} 重置到 ${'$'}{ref.shorthand}`],
  ['ui', 'Previous / next file (file list)',
   '上一个/下一个文件（文件列表）'],
  ['ui', 'The stash itself is unchanged.',
   '暂存本身保持不变。'],
  ['ui', `+${'$'}{leftovers.length - 3} more`,
   `+${'$'}{leftovers.length - 3} 更多`],
  ['ui', `+${'$'}{remaining.length - 3} more`,
   `+${'$'}{remaining.length - 3} 更多`],
  ['ui', `Select ${'$'}{diff.path} to apply`,
   `选择 ${'$'}{diff.path} 以应用`],
  ['ui', `create branch ${'$'}{name.trim()}`,
   `创建分支 ${'$'}{name.trim()}`],
  ['ui', 'Reset branch to its remote?',
   '将分支重置到其远端？'],
  ['ui', 'No files match the filter.',
   '没有匹配过滤条件的文件。'],
  ['ui', 'Stash selected changes',
   '暂存选中的更改'],
  ['ui', 'Filter changed files…',
   '过滤更改的文件…'],
  ['ui', `Checkout ${'$'}{name}`,
   `检出 ${'$'}{name}`],
  ['ui', 'Drop this stash?',
   '丢弃此暂存？'],
  ['ui', 'Hide file filter',
   '隐藏文件过滤'],
  ['ui', 'Pop latest stash',
   '弹出最新暂存'],
  ['ui', 'Clear filter',
   '清除过滤条件'],
  ['ui', 'Commit files',
   '提交文件'],
  ['ui', 'Filter files',
   '过滤文件'],
  ['ui', 'Filter files…',
   '过滤文件…'],
  ['ui', 'Reset branch',
   '重置分支'],
  ['ui', `'Clean'`, `'干净'`, `: 'Clean'}`],
  // --- F7 family + scan blind spots (not in batch1) ---
  ['ui', 'This is a stash. Tick files to apply only those to the working copy.',
   '这是一个暂存。勾选文件即可只将这些文件应用到工作副本。'],
  ['ui', `Pop latest stash: ${'$'}{latestStash.message}`,
   `弹出最新暂存：${'$'}{latestStash.message}`],
  ['ui', 'Pop latest stash (nothing stashed)',
   '弹出最新暂存（当前没有暂存）'],
  ['ui', 'aria-label="Stash"', 'aria-label="暂存"', 'aria-label="Stash"'],
  ['ui', 'Clear filters', '清除过滤条件', '^\\s*Clear filters$'],
  ['ui', `${'$'}{stash.message} — click to preview, right-click for actions`,
   `${'$'}{stash.message} — 点击预览，右键查看更多操作`],
  ['ui', 'Stash this file…', '暂存此文件…'],
  ['ui', `Stash {menuMulti.paths.length} files…`,
   `暂存 {menuMulti.paths.length} 个文件…`],
  ['ui', `'Stash'`, `'暂存'`, `submit\\('Stash'`],
  ['ui', 'Checkout after creating', '创建后检出'],
  ['ui', '— add a message for an annotated tag.',
   '— 为附注标签添加一条消息。'],
  ['ui', 'Show in Finder', '在 Finder 中显示'],
  ['ui', `'Discard'`, `'丢弃'`, `confirmLabel: 'Discard'`],
  ['ui', 'Open the commit\\u2019s files / back to the graph',
   '打开提交的文件 / 返回提交图'],
  // --- batch2.tsv (website + docs) ---
  ['docs', '- [x] Stash: create (whole tree or chosen files), apply, pop (one click from the toolbar), drop; stashes as rows in the graph with their own node and menu; apply single files from a stash · Tags: create (annotated/lightweight), delete, checkout · Submodules: list & update',
   '- [x] 暂存：创建（整棵树或所选文件）、应用、弹出（工具栏一键）、丢弃；暂存作为提交图中的行，带有自己的节点与菜单；可从暂存中应用单个文件 · 标签：创建（附注/轻量）、删除、检出 · 子模块：列出与更新'],
  ['website', 'Angkor Git (AngKorGit) is a fast, free, open-source Git 客户端 and Git GUI for macOS, Windows, and Linux, built native with Tauri v2, Rust and libgit2. Visual commit graphs, side-by-side diff review, visual conflict resolution, and AI assistance.',
   'Angkor Git (AngKorGit) 是一款快速、免费、开源的 Git 客户端与 Git GUI，适用于 macOS、Windows 和 Linux，基于 Tauri v2、Rust 与 libgit2 原生构建。可视化提交图、并排 diff 审查、可视化冲突解决与 AI 辅助。'],
  ['website', '文件历史 is there. Line-level blame is on the list.',
   '文件历史已实现。行级 blame 已在计划中。'],
  ['website', 'AngKorGit · Git 客户端 for macOS, Windows, Linux',
   'AngKorGit · 面向 macOS、Windows、Linux 的 Git 客户端'],
  ['website', 'AngKorGit contributors', 'AngKorGit 贡献者', 'AngKorGit contributors'],
];

// ---------------- skips: [scope, source, category] ----------------
const SKIP = [
  // --- batch1.tsv partial snippets (covered by longer entries in this batch) ---
  ['ui', '). Submodule changes must be discarded inside the submodule repository.', 'partial-snippet：完整词条 `${leftovers.length} change…could not be discarded (${listed}). Submodule…` 覆盖'],
  ['ui', 'cannot be checked out from AngKorGit — open it in the browser instead.', 'partial-snippet：完整词条 `This ${forgeNoun(…) } cannot be checked out…` 覆盖'],
  ['ui', 'Open a pre-filled pull request page for', 'partial-snippet：完整词条 `Open a pre-filled pull request page for ${repo?.headBranch}` 覆盖'],
  ['ui', 'only on the local branch will be lost.', 'partial-snippet：完整词条 `${local.ahead} commit…only on the local branch will be lost.` 覆盖'],
  ['ui', '\\r\\n[could not start shell:', 'partial-snippet：完整词条 `\\r\\n[could not start shell: ${…}]` 覆盖'],
  ['ui', 'AngKorGit error report\\n\\n', 'partial-snippet：完整词条 `AngKorGit error report\\n\\n${error?.name}…` 覆盖'],
  ['ui', 'without leaving AngKorGit', 'partial-snippet：完整词条 `Create a ${prNoun} for ${repo?.headBranch} without leaving AngKorGit` 覆盖'],
  ['ui', 'could not be discarded (', 'partial-snippet：完整词条 `…could not be discarded (${listed}). Submodule…` 覆盖'],
  ['ui', 'could not be discarded:', 'partial-snippet：完整词条 `…could not be discarded: ${listed}` 覆盖'],
  ['ui', 'Worktree ready ·', 'partial-snippet：完整词条 `Worktree ready · ${basename(created)}` 覆盖'],
  ['ui', 'from the stash', 'partial-snippet：Applied…from the stash / Apply ${diff.path} from the stash 完整词条覆盖'],
  ['ui', 'create branch', 'partial-snippet：完整词条 `create branch ${name.trim()}` 覆盖'],
  ['ui', 'staged change', 'partial-snippet：完整词条 `${remaining.length} staged change${…}` / `Discarded ${before} staged change${…}` 覆盖'],
  ['ui', 'Redo failed:', 'partial-snippet：完整词条 `Redo failed: ${…}` 覆盖'],
  ['ui', 'Undo failed:', 'partial-snippet：完整词条 `Undo failed: ${…}` 覆盖'],
  ['ui', 'From commit', 'partial-snippet：完整词条 `From commit ${dialogContext.slice(0, 8)}` 覆盖'],
  ['ui', 'detached @', 'partial-snippet：完整词条 detached @ ${repo.headOid?.slice(0, 8)} / ${wt.headOid…} 覆盖'],
  ['ui', 'At commit', 'partial-snippet：完整词条 `At commit ${dialogContext.slice(0, 8)}` 覆盖'],
  ['ui', 'Create a', 'partial-snippet：完整词条 `Create a ${prNoun} for ${repo?.headBranch}…` 覆盖'],
  ['ui', '无法在 Finder 中显示文件：', 'cjk：已中文化词条残片（dict:776 已译）'],
  ['ui', '无法加载 diff：', 'cjk：已中文化词条残片（dict:137 已译）'],
  // --- batch1.tsv code/css/ident ---
  ['ui', "\${h.header}\\n\${h.lines.map((l) => `\${l.kind === 'addition' ? '+' : l.kind === 'deletion' ? '-' : ' '}\${l.content}`).join('\\n')}",
   'code：diff 文本生成逻辑（CommitDetails.tsx:85），非 UI 文案'],
  ['ui', "\${repoRemotes.map((r) => `\${r.name}=\${r.url}`).join(',')}|\${upstream}",
   'code：仓库指纹序列化（RepositoryPage.tsx:170）'],
  ['ui', `${'$'}{value.slice(0, selectionStart)}\\t${'$'}{value.slice(selectionEnd)}`,
   'code：Tab 键文本处理逻辑（EditorPanel.tsx:144）'],
  ['ui', `${'$'}{(el.scrollTop / el.scrollHeight) * 100}%`,
   'code：滚动百分比计算（DiffMinimap.tsx:140）'],
  ['ui', 'translateY(${item.start - outputMargin}px)', 'css：transform 值（ConflictResolver.tsx:1226）'],
  ['ui', 'translateY(${item.start - scrollMargin}px)', 'css：transform 值（WorkingCopyPanel.tsx:188）'],
  ['ui', 'translateY(${item.start - topMargin}px)', 'css：transform 值（ConflictResolver.tsx:956）'],
  ['ui', `${'$'}{(error as { message?: string }).message ?? error}`,
   'code：纯错误占位符（SettingsDialog.tsx:101）'],
  ['ui', `${'$'}{commit.author.name} <${'$'}{commit.author.email}>`,
   'ident：作者姓名+邮箱格式串（GraphRow.tsx:500），保留原文'],
  ['ui', "Basic \${btoa(`\${identity}:\${token}`)}",
   'code：HTTP Basic 认证头（AccountsTab.tsx:129）'],
  ['ui', `${'$'}{remoteName ?? 'origin'}/`,
   'code：远端分支前缀拼接（CreatePrDialog.tsx:82）'],
  ['ui', "\${w.name}\${w.branch ? ` · \${w.branch}` : ''}",
   'code：纯占位符拼接（CommandPalette.tsx:398）'],
  // --- batch1.tsv t2-adjudicated skips (reused from zh-dict/batches/ui/skip-ui.tsv) ---
  ['ui', `Cherry-picked ${'$'}{oids.length} commits (demo)`, 'demo：演示模式 toast，e2e 断言引用（smoke.spec.ts:150），保持英文'],
  ['ui', 'Cherry-picked (demo)', 'demo：演示模式 toast，e2e 断言引用（smoke.spec.ts:130），保持英文'],
  ['ui', 'Merged ${name} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Rebased onto ${upstream} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Rebase complete (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Pushed to ${remote} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Fetched ${remote} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Pulled ${branch} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Pushed tag ${tag} (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', 'Reverted (demo)', 'demo：演示模式 toast（ipc.ts demo 分支），保持英文'],
  ['ui', "'JetBrains Mono', monospace", 'css：字体族字符串（TerminalPanel.tsx:19）'],
  ['ui', 'Bearer ${token}', 'code：HTTP Authorization 认证头（AccountsTab.tsx:146）'],
  ['ui', '(folder: TreeFolder', 'code：TS 函数签名（FileTree.tsx:109）被 JSX 扫描误报'],
  ['ui', '): number', 'code：TS 函数签名（ConflictResolver.tsx:113）被 JSX 扫描误报'],
  ['ui', '): string', 'code：TS 函数签名（AccountsTab.tsx:99）被 JSX 扫描误报'],
  ['ui', '\\b \\b', 'code：终端退格控制序列（TerminalPanel.tsx:45）'],
  ['ui', 'gitlab.example.com', 'ident：示例占位域名（placeholder），保留英文'],
  ['ui', 'v1.0.0', 'ident：版本号示例（placeholder），保留原文'],
  ['ui', 'sk-…', 'ident：API 密钥前缀示例（placeholder），保留原文'],
  ['ui', 'Esc', 'key：快捷键键名，保留原文'],
  ['ui', 'Home / End', 'key：快捷键键名，保留原文'],
  ['ui', 'A / C', 'key：快捷键键名，保留原文'],
  ['ui', 'K / P', 'key：快捷键键名，保留原文'],
  ['ui', 'P / N', 'key：快捷键键名，保留原文'],
  ['ui', 'SSH', 'term：协议名，保留英文'],
  ['ui', 'AngKorGit v${version}', 'brand：品牌名 + 版本号，保留原文'],
  // --- batch1.tsv CJK re-scans (dict targets already in files) ---
  ['ui', '使用本机已安装的 AI CLI——Claude Code、Codex、Gemini CLI、OpenCode 或 Antigravity——以其自身的登录与配额运行，无需 API 密钥。', 'cjk：已中文化（dict 词条 target 重扫）'],
  ['ui', 'AI 请求失败：${(error as { message?: string } | null)?.message ?? String(error)}', 'cjk：已中文化（dict:140 target）'],
  ['ui', '请安装 Claude Code、Codex CLI、Gemini CLI、OpenCode 或 Antigravity CLI，然后重新扫描。', 'cjk：已中文化'],
  ['ui', '具有 read:repository:bitbucket + write:repository:bitbucket 权限范围的 API 令牌', 'cjk：已中文化'],
  ['ui', '无法切换到 ${main.name}：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:775 target）'],
  ['ui', '无法打开 ${held.name}：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:139 target）'],
  ['ui', '无法在 Finder 中显示文件：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:776 target）'],
  ['ui', '无法打开 ${wt.name}：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:778 target）'],
  ['ui', '无法打开 ${file}：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:781 target）'],
  ['ui', '无法读取 ${file}：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:782 target）'],
  ['ui', '${label} 失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:124 target）'],
  ['ui', '无法加载 diff：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:137 target）'],
  ['ui', '丢弃失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:749 target）'],
  ['ui', '中止失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:143 target）'],
  ['ui', '保存失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:790 target）'],
  ['ui', '克隆失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:378 target）'],
  ['ui', '刷新失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:144 target）'],
  ['ui', '变基失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:786 target）'],
  ['ui', '合并失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:788 target）'],
  ['ui', '应用失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:789 target）'],
  ['ui', '拣选失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:527 target）'],
  ['ui', '提交失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:557 target）'],
  ['ui', '无法打开：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:784 target）'],
  ['ui', '更新失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:141 target）'],
  ['ui', '清除失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:370 target）'],
  ['ui', '移除失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:787 target）'],
  ['ui', '继续失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:369 target）'],
  ['ui', '连接失败：${(error as { message?: string }).message ?? error}', 'cjk：已中文化（dict:785 target）'],
  ['ui', '将 user.name 和 user.email 写入 ${repo.name}/.git/config', 'cjk：已中文化（dict target）'],
  ['ui', '具有“read_repository” + “write_repository”权限范围的个人访问令牌', 'cjk：已中文化（dict target）'],
  ['ui', 'AngKorGit 崩溃了：', 'cjk：已中文化（ErrorBoundary.tsx:17）'],
  ['ui', 'Atlassian 账户邮箱', 'cjk：已中文化（AccountsTab.tsx:491）'],
  // --- batch2.tsv skips ---
  ['website', '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">', 'code：SVG 属性片段（icons.ts:44）'],
  ['website', '一个词，AngKorGit。也有人写作 Angkor Git、angkorgit 或 GitAngkor，指的都是这个应用。angkorgit.app 是唯一的官方网站，代码托管在 GitHub 的 cheat2001/angkorgit 仓库。', 'cjk：已中文化（Questions.astro:6）'],
  ['website', '-o "$env:TEMP\\\\AngKorGit-setup.exe"; Start-Process "$env:TEMP\\\\AngKorGit-setup.exe"', 'command：PowerShell 命令（Install.astro:68）'],
  ['website', 'Start-Process "$env:TEMP\\\\AngKorGit-setup.exe"', 'command：PowerShell 命令（Install.astro:66）'],
  ['website', '-o "$env:TEMP\\\\AngKorGit-setup.exe"', 'command：PowerShell 命令（Install.astro:65）'],
  ['website', 'AngKorGit（Angkor Git）——快速、免费的 Git 客户端与 Git GUI，支持 macOS、Windows 和 Linux', 'cjk：已中文化（site.ts:21）'],
  ['website', 'return render(rows, { palette, animate: true });', 'code：mock 演示代码（Conflicts.astro:10）'],
  ['website', 'export function drawGraph(rows: Row[]) {', 'code：mock 演示代码（Conflicts.astro:8）'],
  ['website', "import { render } from './renderer';", 'code：mock 演示代码（Conflicts.astro:6）'],
  ['website', 'const palette = useThemePalette();', 'code：mock 演示代码（Conflicts.astro:10）'],
  ['website', 'return render(rows, { colors });', 'code：mock 演示代码（Conflicts.astro:11）'],
  ['website', 'const colors = legacyColors();', 'code：mock 演示代码（Conflicts.astro:11）'],
  ['website', 'Tauri 2 · Rust · libgit2 · React', 'brand：技术栈名称列表，保留原文（Footer.astro:59）'],
  ['website', 'scale(${frame.clientWidth / w})', 'code：CSS transform 表达式（Frame.astro:17）'],
  ['website', 'Intel 与 Apple Silicon，单文件', 'cjk：已中文化（Install.astro:10）'],
  ['website', 'WIP on main: experiment …', 'demo：mock stash 消息示例，保持英文（Sidebar.astro:29）'],
  ['website', 'AngKorGit 还是 Angkor Git？', 'cjk：已中文化（Questions.astro:5）'],
  ['website', 'feature/* → feat(scope):', 'ident：分支前缀→提交规范示例，保留原文（AiSection.astro:63）'],
  ['website', 'angkorgit-feature-di…', 'demo：mock 分支名（Sidebar.astro:18）'],
  ['website', 'angkorgit-fix-stash…', 'demo：mock 分支名（Sidebar.astro:19）'],
  ['website', 'macOS, Windows, Linux', 'brand：平台名称列表，保留原文（Base.astro:24）'],
  ['website', '## 1. DNS（Hostinger）', 'cjk：已中文化（Launch-Checklist.md:6）'],
  ['website', 'AppImage、.deb 和 .rpm', 'ident：打包格式名称，保留原文（Install.astro:22）'],
  ['website', 'Windows（PowerShell）', 'cjk：已中文化（Install.astro:63）'],
  ['website', 'Mac（Homebrew）', 'cjk：已中文化（Install.astro:13）'],
  ['website', 'angkorgit.app', 'ident：域名，保留原文（HeroGraph.astro:5）'],
  ['website', 'drawGraph.ts', 'ident：文件名，保留原文（Conflicts.astro:8）'],
  ['website', 'blame 视图', 'cjk：已中文化（SpecSheet.astro:71）'],
  ['website', 'HEAD', 'term：Git 术语，保留原文（Commit.astro:27）'],
  ['website', 'init', 'code：命令/标识符，保留原文（Story.astro:6）'],
];

// ---------------- sort long-source-first (§4.7) ----------------
E.sort((a, b) => b[1].length - a[1].length || (a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0));

// ---------------- validation ----------------
const srcs = E.map((e) => e[1]);
const dup = srcs.filter((s, i) => srcs.indexOf(s) !== i);
if (dup.length) throw new Error(`duplicate sources: ${dup.join(' | ')}`);
const skipSrcs = new Set(SKIP.map((s) => s[1]));
for (const e of E) {
  if (skipSrcs.has(e[1])) throw new Error(`entry also in SKIP: ${e[1]}`);
  if (!/[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]/.test(e[2])) throw new Error(`target has no CJK: ${e[1]}`);
  if (!/\s/.test(e[1]) && !e[3]) throw new Error(`no-space source without anchor: ${e[1]}`);
}
// coverage vs forward batches
for (const [bn] of [['batch1.tsv'], ['batch2.tsv']]) {
  const rows = raw(`zh-dict/research/${bn}`).split(/\r?\n/).filter((l) => l && !l.startsWith('#')).map((l) => l.split('\t'));
  for (const row of rows) {
    const src = row[1];
    if (skipSrcs.has(src)) continue;
    const covered = srcs.includes(src) || srcs.some((s) => s.includes(src));
    if (!covered) { console.error(`UNCOVERED in ${bn}: ${src}`); process.exit(1); }
  }
}
// F7 family presence
const f7 = [
  'Reset branch to its remote?', 'Reset branch', 'Checkout ${name}', 'Reset ${name} to ${ref.shorthand}',
  'Pop latest stash', 'Stash this file…', 'Stash selected changes', 'Only this file is stashed. Everything else stays in your working copy.',
  'Applied ${files.length} files from the stash', 'The stash itself is unchanged.', 'This is a stash. Tick files to apply only those to the working copy.',
  'Drop this stash?', 'Clear filter', 'Commit files', 'aria-label="Stash"', '${stash.message} — click to preview, right-click for actions',
];
for (const s of f7) {
  if (!srcs.includes(s) && !srcs.some((x) => x.includes(s))) { console.error(`F7 missing: ${s}`); process.exit(1); }
}

// ---------------- write ----------------
mkdirSync(here, { recursive: true });
const head = [
  '# v011b ui-web 翻译批次（translator-a · t17）：forward batch1.tsv(ui 153) + batch2.tsv(website+docs 35) 全处置 + F7 家族 + 扫描盲区',
  '# 列：scope<TAB>source<TAB>target<TAB>anchor(可选)；source 按长度降序（长串优先，契约 §4.7）',
  `# 词条 ${E.length} 条（ui ${E.filter((e) => e[0] === 'ui').length} / website ${E.filter((e) => e[0] === 'website').length} / docs ${E.filter((e) => e[0] === 'docs').length}）；skip ${SKIP.length} 条见 skip.tsv`,
  '# 占位符 ${...}/{...} 与 \\n/\\r\\n 转义原样保留；无空格裸词条全部带 anchor',
];
const lines = [...head, ...E.map(([s, src, tgt, a]) => `${s}\t${src}\t${tgt}${a ? `\t${a}` : ''}`)];
writeFileSync(join(here, 'batch.tsv'), lines.join('\n') + '\n', 'utf8');
const skipHead = ['# skip.tsv — v011b ui-web 不可译清单（batch1/batch2 裁决 + t2 复用）', '# 列：scope<TAB>source<TAB>category'];
writeFileSync(join(here, 'skip.tsv'), [...skipHead, ...SKIP.map(([s, src, c]) => `${s}\t${src}\t${c}`)].join('\n') + '\n', 'utf8');
console.log(`OK entries=${E.length} skips=${SKIP.length}`);